ALTER TABLE `pages`
  ADD COLUMN IF NOT EXISTS `button_text` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `button_link` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `services`
  ADD COLUMN IF NOT EXISTS `button_text` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `button_link` VARCHAR(255) DEFAULT NULL;
